server.port=8080

spring.application.name=api-gateway


spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/bookstore_user/add_cart_item/**,/bookstore_user/cart_item_quantity/**,/bookstore_user/remove_cart_item/**,/bookstore_user/get_cart_items,/bookstore_user/add_wish_list/**,/bookstore_user/remove_wishlist_item/**,/bookstore_user/get_wishlist_items,/bookstore_user/add/order


spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/bookstore_user/**


spring.cloud.gateway.server.webflux.routes[2].id=book-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://book-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/bookstore_book/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/